"""load applications

Revision ID: 244e08e318ae
Revises: 98b0fb2312e5
Create Date: 2026-05-21 22:50:02.861078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244e08e318ae'
down_revision: Union[str, Sequence[str], None] = '98b0fb2312e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_adr', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preferred_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desired_salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('license_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_countries', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adr_certificate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('driver_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_profiles_pkey'))
    )
    op.create_table('company_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fleet_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('company_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_profiles_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], name=op.f('applications_company_profile_id_fkey')),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], name=op.f('applications_driver_profile_id_fkey')),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f('applications_job_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('applications_pkey'))
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('messages_sender_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], name=op.f('jobs_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], name=op.f('saved_jobs_driver_profile_id_fkey')),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f('saved_jobs_job_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_jobs_pkey'))
    )
    op.create_table('job_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pickup_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adr_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('truck_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], name=op.f('job_posts_company_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_posts_pkey'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('conversations_application_id_fkey')),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], name=op.f('conversations_company_user_id_fkey')),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('conversations_driver_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###
